# version: "3.9"

services:
  api:
    build: .
    # container_name: app
    environment:
      - PYTHON_VERSION=3.13
    ports:
      - 8080:8080
    networks:
      - frontnet
    restart: always

  proxy:
    build: proxy
    restart: always
    ports:
      - 8000:8000
    depends_on: 
      - api
    networks:
      - frontnet

networks:
  frontnet: